### ISSUE TITLE
error on execute 

### ISSUE THREAD

**Issue by Cormoran96** [RaymiiOrg/librenms-api-alerts#1]
```bash
 python2 open_alerts.py
Traceback (most recent call last):
  File "open_alerts.py", line 118, in <module>
    alert_rule = librenms_api.get_alert_rule(alert["rule_id"])
  File "open_alerts.py", line 61, in get_alert_rule
    rule_req = urllib2.Request(self.api_url + "rules/" + rule_id, headers=self.request_headers)
TypeError: cannot concatenate 'str' and 'int' objects
```

**Comment by Durzzo** [comment]
I have exactly this same issue. How do we resolve?

**Comment by Cormoran96** [comment]
I don't resolve it. I don't search the answer

**Comment by Durzzo** [comment]
I'm not very familiar with python syntax (I'm just a bash guy) but I might be able to fix it if needed. Would be much more efficient if Raymii could take a look though. I will check back for an update from Raymii later and we can take it from there.
